#184639058 Server starter Scripts && ES6 configuration
atlp-rwanda/rca-barefoot-team6-bn pull request #11
Opened 2023-03-13 10:30 UTC by didiermun

#### What does this PR do?

This PR serves to add extra scripts for the express server. It also enables es6 for imports for the project.

#### Description of the task to be completed?

Has the following functionalities:

-  Adds dev script.
- Adds build script.
- Enabbles ES6 usage.

#### How should this be manually tested?

Clone the project, and install all the dependencies. Run ``npm run dev``, ``npm run start``, or ``npm run build``. You can also trying importing files with the import statement not the require.

#### Any background context you want to provide?

Not any

#### What are the relevant pivotal tracker stories?

#### Screenshots (if appropriate)

---

2023-03-13 11:38 UTC, divinirakiza approved these changes

2023-03-13 11:52 UTC, Nkbtemmy approved these changes

2023-03-13 12:59 UTC, oreste-abizera approved these changes

2023-03-14 13:49 UTC, Nkbtemmy commented
Please squash your commits into one commit; and see why your test is failing while on develop passed

2023-03-14 13:52 UTC, Nkbtemmy requested changes

2023-03-14 13:52 UTC, Nkbtemmy commented on yarn.lock
Decide to use npm or yarn

2023-03-15 08:01 UTC, merged