#184638373 user login
atlp-rwanda/rca-barefoot-team6-bn pull request #18
Opened 2023-03-16 09:53 UTC by oreste-abizera

#### What does this PR do?
 
 implements user login

#### Description of  the task to be completed?

A user can log into the Barefoot Nomad application via email & password

#### How should this be manually tested?

- checkout into `ft-user-login-184638373` branch and install dependencies including jsonwebtoken
- add `JWT_SECRET` and `JWT_EXPIRES_IN` in the env file
- register a user and then send a POST request to ${Basic URL}/api/users/login and provide email and password in the body

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker stories?

[#184638373](https://www.pivotaltracker.com/story/show/184638373)

#### Screenshots (if appropriate)
...

2023-03-18 09:42 UTC, felixdusengimana reviewed
LGTM!

2023-03-18 09:43 UTC, felixdusengimana approved these changes

2023-03-21 12:42 UTC, felixdusengimana requested changes

2023-03-21 12:42 UTC, felixdusengimana commented on package.json
> +    "swaggiffy": "^1.0.5"
remove this package "swaggiffy"

2023-03-21 13:20 UTC, dushimsam approved these changes
Looks great

2023-03-22 14:03 UTC, oreste-abizera commented on package.json
> +    "swaggiffy": "^1.0.5"
removed

2023-03-25 21:28 UTC, dianKoliva approved these changes

2023-03-26 08:31 UTC, edine-noella approved these changes

2023-03-26 12:26 UTC, felixdusengimana approved these changes
LGTM

2023-03-27 12:00 UTC, Nkbtemmy requested changes
Please remove unwanted files and folders like swaggify file and swagger folder which is out of src folder

2023-03-27 13:37 UTC, honorine22 approved these changes

2023-03-27 14:03 UTC, oreste-abizera commented
> Please remove unwanted files and folders like swaggify file and swagger folder which is out of src folder

Done

2023-03-27 19:11 UTC, Nkbtemmy approved these changes

2023-03-27 19:15 UTC, merged