Ft:lougout 184638376
atlp-rwanda/rca-barefoot-team6-bn pull request #20
Opened 2023-03-16 13:14 UTC by dianKoliva

#### What does this PR do?
It adds the logout feature
 ...

#### Description of  the task to be completed?
The user will be able to logout
...

#### How should this be manually tested?
get all tokens "/api/users/tokens"
update toke "/api/users/logout/id" where id is the id of the token to inactivate
...

#### Any background context you want to provide?

...

#### What are the relevant pivotal tracker stories?
##184638376
...

#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/87997450/225627504-87f91d03-64fa-496b-8318-2c1b2d26c103.png)
![image](https://user-images.githubusercontent.com/87997450/225627686-7f523e8d-fb08-445c-8e31-5bb858786b5c.png)

...

2023-03-16 16:16 UTC, oreste-abizera requested changes
Great work on the implemented work! However, we must also ensure that the generated token is added to the database as well. Additionally, in order to enable logging out functionality, we'll need to create a middleware that checks whether the user is authorized. Also in the logout function, we can use the auth token passed in headers to find the associated token instead of using the user id.

2023-03-16 16:16 UTC, oreste-abizera commented on src/controllers/userController.js
> +    await Token.create({ userId: user.id, state: 'active' });
You should store that token in the database as well

2023-03-16 16:16 UTC, oreste-abizera commented on src/controllers/userController.js
> +    const token = await Token.findOne({ where: { id } });
You need to find by auth token passed in the headers, not by the user id

2023-03-17 11:22 UTC, honorine22 approved these changes

2023-03-20 11:00 UTC, oreste-abizera approved these changes

2023-03-20 13:52 UTC, felixdusengimana requested changes
Can you add swagger documentation of your API

2023-03-26 21:42 UTC, Nkbtemmy approved these changes

2023-03-26 21:42 UTC, merged