Ft register user confirm 184638320
atlp-rwanda/rca-barefoot-team6-bn pull request #23
Opened 2023-03-17 16:38 UTC by honorine22

#### What does this PR do?
 Verify registered user by sending email
 ...

#### Description of  the task to be completed?
Implementing email verification
...

#### How should this be manually tested?
Checkout to ft-register-user-confirm-184638320 and Use Postman to create user with this route: ${Basic URL}/api/users
Get that user with ${Basic URL}/api/users to view his token
Paste the token in this route ${Basic URL}/api/users/verify-email/${token}
...

#### Any background context you want to provide?
Create app password from your google account to get a password to be used as APP_PASS env variable
Ensure also that you have EMAIL variable in env file
Then you will be able to send emails to the created users
...

#### What are the relevant pivotal tracker stories?
184638371
...

#### Screenshots (if appropriate)

...

2023-03-17 17:50 UTC, felixdusengimana commented on src/database/models/user.js
Can you add 
```
- provider
- providerId
```
properties for facebook and google login

2023-03-19 11:16 UTC, oreste-abizera approved these changes

2023-03-19 16:32 UTC, dianKoliva approved these changes

2023-03-19 19:35 UTC, dushimsam approved these changes
Changes looks great

2023-03-19 21:19 UTC, felixdusengimana requested changes
Can you add your swagger API documentation using the hello example given

2023-03-20 09:52 UTC, felixdusengimana approved these changes

2023-03-23 16:12 UTC, closed without merging