feat: login with socil works fine
atlp-rwanda/rca-barefoot-team6-bn pull request #31
Opened 2023-03-24 13:50 UTC by felixdusengimana

#### What does this PR do?
 
Added login with facebook and google functionalities

#### Description of the task to be completed?

#### How should this be manually tested?

Check out this branch, run `npm install`, 
Make sure your .env have all properties in `.env.example`
then go to `{BASE_URL}/api/users/auth/google` or `{BASE_URL}/api/users/auth/facebook` and then you can login in with your credentials. 

#### Any background context you want to provide?

None

#### What are the relevant pivotal tracker stories?

# 184638374

#### Screenshots (if appropriate)

...

2023-03-26 13:29 UTC, oreste-abizera commented on .env.example
can you re-add EMAIL and APP_PASS variables in .env.example

2023-03-27 11:28 UTC, dushimsam approved these changes
LGTM

2023-03-27 13:37 UTC, honorine22 approved these changes

2023-03-27 15:05 UTC, oreste-abizera approved these changes

2023-03-28 10:33 UTC, Nkbtemmy requested changes

2023-03-28 10:33 UTC, Nkbtemmy commented on .env.example
> +BACKEND_URL=
Use BASE_URL instead of this; and update where you used BACKEND_URL

2023-03-28 10:33 UTC, Nkbtemmy commented on .env.example
> +FRONTEND_URL=
Also, this have been specified as WEB_URL

2023-03-28 14:33 UTC, Nkbtemmy approved these changes

2023-03-28 14:33 UTC, merged