feat: create CRUD operations for hotels
atlp-rwanda/rca-barefoot-team6-bn pull request #37
Opened 2023-03-28 09:54 UTC by dushimsam

#### What does this PR do?
 
Contains the CRUD operations for Hotel's model.

#### Description of  the task to be completed?

The task is comprised of CREATE, GET ALL, GET & UPDATE APIs for hotel's model

#### How should this be manually tested?

 1. Run the project - npm run dev
 2. Open the swagger editor on [http](http://localhost:[PORT]/api-docs)
 3. Run the APIs on the Hotel's section
 
#### Any background context you want to provide?

...

#### What are the relevant pivotal tracker stories?

#184779354

#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/66276301/228199039-f41fec6b-b64d-401c-bc82-369e6d224f70.png)
![image](https://user-images.githubusercontent.com/66276301/228199181-e1e2b03e-b3d3-431c-87a3-e6193e2ece4f.png)
![image](https://user-images.githubusercontent.com/66276301/228199307-626fe4d5-e954-426e-b687-c01f5e33d0d3.png)
![image](https://user-images.githubusercontent.com/66276301/228199452-9c15ef82-6b0c-4e43-9aae-9602802af2ad.png)
![image](https://user-images.githubusercontent.com/66276301/228199611-048490cb-826c-47b5-a300-846151347639.png)

...

2023-03-28 10:21 UTC, honorine22 approved these changes
Great work!

2023-03-31 13:54 UTC, Nkbtemmy requested changes

2023-03-31 13:54 UTC, Nkbtemmy commented on src/database/migrations/20230327163941-create-hotel.js
> +      },
what if you have latitude and longitude separately !!

2023-03-31 13:54 UTC, Nkbtemmy commented on src/database/migrations/20230327163941-create-hotel.js
> +      },
when yo do that make sure they have correct datatypes

2023-03-31 13:54 UTC, Nkbtemmy commented on src/database/models/hotel.js
> +  },
Same as here

2023-03-31 13:54 UTC, Nkbtemmy commented on src/database/seeders/20230327164033-sample-hotels.js
> +          coordinates: "POINT (23.456789 1.234567)",
....

2023-03-31 15:00 UTC, dushimsam commented on src/database/migrations/20230327163941-create-hotel.js
> +      },
Done

![image](https://user-images.githubusercontent.com/66276301/229156421-ef874fac-79fe-4765-a9ae-51e02b4bf6b9.png)

![image](https://user-images.githubusercontent.com/66276301/229156328-192e2a61-417a-4fb5-8b81-741896a264ac.png)

It's working in posting data via other channels such as APIs, but failing when seeding data.

![image](https://user-images.githubusercontent.com/66276301/229156755-e99f3536-3124-4655-94c3-2891b7b472a5.png)

2023-04-01 17:48 UTC, Nkbtemmy approved these changes

2023-04-02 16:38 UTC, oreste-abizera approved these changes
LGTM

2023-04-02 17:27 UTC, merged