chore:.env setup and added Hound badge
atlp-rwanda/rca-barefoot-team6-bn pull request #5
Opened 2023-03-10 12:33 UTC by dianKoliva

What does this PR do?
.env setup and attaches Hound badge the readme
Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2023-03-10 16:16 UTC, Nkbtemmy approved these changes
Please rebase develop

2023-03-10 16:17 UTC, Nkbtemmy requested changes
please rebase develop

2023-03-12 18:11 UTC, edine-noella approved these changes

2023-03-13 05:36 UTC, divinirakiza approved these changes

2023-03-13 10:12 UTC, didiermun approved these changes
Looks good to go

2023-03-15 17:27 UTC, closed without merging