chore(docker): create Dockerfile for node
atlp-rwanda/rca-barefoot-team6-bn pull request #6
Opened 2023-03-10 12:54 UTC by honorine22

**What does this PR do?**
Run Express server in Docker container

**Description of Task to be completed?**
Install Node image with docker
Define the app location in the container
Install app dependencies
Copy current directory files into the image
Expose the application port to be run on in a container
Tell the docker command to run

**How should this be manually tested?**
After cloning the repository, cd into it and RUN docker build -t node-app . -f docker/Dockerfile
RUN docker run -p 3000:8080 --name node-app-container node-app
You will see the server running into node-app-container

**Any background context you want to provide?**
You must have docker installed on your computer to test this task.

**What are the relevant pivotal tracker/Trello stories?**
#184638368

2023-03-10 13:11 UTC, Nkbtemmy requested changes
Sure; you did a great job; but I would like to have those docker files outside of the Docker folder(i want them to be on the same level as package.json); also I would recommend adding also docker-compose file; and then deleting that docker folder; I don't want it !!

2023-03-12 18:10 UTC, edine-noella approved these changes

2023-03-12 20:24 UTC, oreste-abizera approved these changes
LGTM

2023-03-13 09:39 UTC, Nkbtemmy approved these changes

2023-03-13 09:39 UTC, merged